Repository wikimedia/change-propagation, pull requests merged in 2018-05, with the labels that each got.

#260 Cleanup: Remove oldEmitterId and old retry topic names
  lib/base_executor.js
  lib/retry_executor.js
Labels: hygiene

#263 Resubscribe to proper list of topics once the list changes
  lib/rule_subscriber.js
Labels: bug

#264 Use the latest service-runner v2.6.1
  package.json
Labels: hygiene

#248 Added tests for delayed execution
  config.jobqueue.wikimedia.yaml
  lib/base_executor.js
  test/feature/job_rules.js
  test/utils/common.js
Labels: tests

#268 Only check the pending messages for lower offset for a correct topic
  lib/base_executor.js
Labels: bug

#269 Commit properly for all the topics subscribed
  lib/base_executor.js
Labels: bug

#270 Commit the latest possible offset
  lib/base_executor.js
Labels: bug

#266 Emit a revision-score event
  config.example.wikimedia.yaml
  lib/base_executor.js
  sys/ores_updates.js
  test/feature/static_rules.js
  test/feature/update_rules.js
  test/utils/clean_kafka.sh
Labels: new feature
