Repository wikimedia/change-propagation, pull requests merged in 2018-07, with the labels that each got.

#278 Allow for events to be blacklisted
  config.example.wikimedia.yaml
  lib/base_executor.js
  lib/utils.js
  test/feature/update_rules.js
Labels: config change, enhancement

#279 Some random test tweaks
  test/feature/job_rules.js
  test/feature/update_rules.js
  test/utils/common.js
Labels: tests

#281 Release v0.9.0
  package.json
Labels: release
