Repository wikimedia/change-propagation, pull requests merged in 2018-04, with the labels that each got.

#245 Fixed the new metrics names. Again
  lib/retry_executor.js
  lib/rule_executor.js
Labels: bug

#246 Fixed deduplication key calculation for multi-topic rules
  lib/rule_executor.js
Labels: bug

#251 Record HTML errors from MW in retry message
  lib/base_executor.js
Labels: enhancement

#254 Remove JSCS check - it's deprecated and replaced by ESLint
  .jscs.json
  package.json
  test/index.js
Labels: hygiene, tests

#256 Support `exclude_topics` config stanza for array and regex rules
  config.test.yaml
  lib/rule.js
  test/feature/static_rules.js
  test/utils/clean_kafka.sh
Labels: new feature

#257 Commit offsets for unmatched messages from time to time
  lib/base_executor.js
Labels: enhancement

#258 Release v0.8.1
  package.json
Labels: release

#259 Log proper topic list we're subscribing to for regex rules
  lib/rule_subscriber.js
Labels: bug
