Repository wikimedia/change-propagation, pull requests merged in 2019-03, with the labels that each got.

#308 Replace `json-stable-stringify` with `fast-json-stable-stringify`
  lib/rule.js
  lib/rule_subscriber.js
  package.json
Labels: enhancement, hygiene

#307 Add blubber pipeline stanzas
  .pipeline/blubber.yaml
Labels: enhancement

#310 Update dependencies, switch istanbul to nyc.
  .gitignore
  .jshintignore
  .jshintrc
  .mocharc.yaml
  package.json
  sys/kafka.js
  test/mocha.opts
  test/utils/clean_kafka.sh
  test/utils/common.js
Labels: hygiene, release, tests

#309 Create a mock kafka factory to enable unit tests without Kafka
  .travis.yml
  config.test.yaml
  lib/base_executor.js
  lib/kafka_factory.js
  package.json
  sys/kafka.js
  test/feature/job_rules.js
  test/feature/static_rules.js
  test/feature/update_rules.js
  test/utils/changeProp.js
  test/utils/clean_kafka.sh
  test/utils/common.js
  test/utils/mock_kafka_factory.js
  test/utils/test_topics
Labels: enhancement, tests

#311 Mock redis for unit tests.
  config.example.wikimedia.yaml
  config.jobqueue.wikimedia.yaml
  config.test.yaml
  lib/base_executor.js
  package.json
  test/utils/changeProp.js
  test/utils/common.js
Labels: config change, enhancement, tests

#312 Enable librdkafka error logging for a producer.
  lib/kafka_factory.js
Labels: hygiene
